Code formatting: spaces instead of tabs

diff --git a/snappi-server/rootfs/etc/init.d/S45wpasupplicant b/snappi-server/rootfs/etc/init.d/S45wpasupplicant
--- a/snappi-server/rootfs/etc/init.d/S45wpasupplicant
+++ b/snappi-server/rootfs/etc/init.d/S45wpasupplicant
@@ -9,24 +9,24 @@ PIDFILE="/var/run/$DAEMON.pid"
 [ -f /etc/wpa_supplicant.conf ] || exit 0
 
 case "$1" in
-	start)
-		printf "Starting $DAEMON: "
-		start-stop-daemon -S -p "$PIDFILE" -x "/usr/sbin/$DAEMON" -- \
-			-P "$PIDFILE" -q -B -i wlan0 -f /var/log/$DAEMON.log -c /etc/$DAEMON.conf
-		[ $? = 0 ] && echo "OK" || echo "FAIL"
-		;;
-	stop)
-		printf "Stopping $DAEMON: "
-		start-stop-daemon -K -q -p "$PIDFILE" -x "/usr/sbin/$DAEMON"
-		[ $? = 0 ] && echo "OK" || echo "FAIL"
-		;;
-	restart|reload)
-		$0 stop
-		$0 start
-		;;
-	*)
-		echo "Usage: $0 {start|stop|restart}"
-		exit 1
+    start)
+        printf "Starting $DAEMON: "
+        start-stop-daemon -S -p "$PIDFILE" -x "/usr/sbin/$DAEMON" -- \
+            -P "$PIDFILE" -q -B -i wlan0 -f /var/log/$DAEMON.log -c /etc/$DAEMON.conf
+        [ $? = 0 ] && echo "OK" || echo "FAIL"
+        ;;
+    stop)
+        printf "Stopping $DAEMON: "
+        start-stop-daemon -K -q -p "$PIDFILE" -x "/usr/sbin/$DAEMON"
+        [ $? = 0 ] && echo "OK" || echo "FAIL"
+        ;;
+    restart|reload)
+        $0 stop
+        $0 start
+        ;;
+    *)
+        echo "Usage: $0 {start|stop|restart}"
+        exit 1
 esac
 
 exit 0
diff --git a/snappi-server/rootfs/etc/init.d/S91jacktrip b/snappi-server/rootfs/etc/init.d/S91jacktrip
--- a/snappi-server/rootfs/etc/init.d/S91jacktrip
+++ b/snappi-server/rootfs/etc/init.d/S91jacktrip
@@ -7,24 +7,24 @@ DAEMON="jacktrip"
 PIDFILE="/var/run/$DAEMON.pid"
 
 case "$1" in
-	start)
-		printf "Starting $DAEMON: "
+    start)
+        printf "Starting $DAEMON: "
         start-stop-daemon -b -S -m -O /var/log/$DAEMON.log -c snappi:audio -p "$PIDFILE" --exec /usr/bin/$DAEMON -- \
             -s --receivechannels 8 --sendchannels 1 --udprt
-		[ $? = 0 ] && echo "OK" || echo "FAIL"
-		;;
-	stop)
-		printf "Stopping $DAEMON: "
-		start-stop-daemon -K -q -p "$PIDFILE" -x "/usr/bin/$DAEMON"
-		[ $? = 0 ] && echo "OK" || echo "FAIL"
-		;;
-	restart|reload)
-		$0 stop
-		$0 start
-		;;
-	*)
-		echo "Usage: $0 {start|stop|restart}"
-		exit 1
+        [ $? = 0 ] && echo "OK" || echo "FAIL"
+        ;;
+    stop)
+        printf "Stopping $DAEMON: "
+        start-stop-daemon -K -q -p "$PIDFILE" -x "/usr/bin/$DAEMON"
+        [ $? = 0 ] && echo "OK" || echo "FAIL"
+        ;;
+    restart|reload)
+        $0 stop
+        $0 start
+        ;;
+    *)
+        echo "Usage: $0 {start|stop|restart}"
+        exit 1
 esac
 
 exit 0
